/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerRouteImport } from './routes/career'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GreatnessRouteImport } from './routes/greatness'
import { Route as IplRouteImport } from './routes/ipl'
import { Route as MahiratRouteImport } from './routes/mahirat'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RohiratRouteImport } from './routes/rohirat'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as VirushkaRouteImport } from './routes/virushka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GreatnessRoute = GreatnessRouteImport.update({
  id: '/greatness',
  path: '/greatness',
  getParentRoute: () => rootRouteImport,
} as any)
const IplRoute = IplRouteImport.update({
  id: '/ipl',
  path: '/ipl',
  getParentRoute: () => rootRouteImport,
} as any)
const MahiratRoute = MahiratRouteImport.update({
  id: '/mahirat',
  path: '/mahirat',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RohiratRoute = RohiratRouteImport.update({
  id: '/rohirat',
  path: '/rohirat',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const VirushkaRoute = VirushkaRouteImport.update({
  id: '/virushka',
  path: '/virushka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/gallery': typeof GalleryRoute
  '/greatness': typeof GreatnessRoute
  '/ipl': typeof IplRoute
  '/mahirat': typeof MahiratRoute
  '/records': typeof RecordsRoute
  '/rohirat': typeof RohiratRoute
  '/stats': typeof StatsRoute
  '/trophies': typeof TrophiesRoute
  '/virushka': typeof VirushkaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/gallery': typeof GalleryRoute
  '/greatness': typeof GreatnessRoute
  '/ipl': typeof IplRoute
  '/mahirat': typeof MahiratRoute
  '/records': typeof RecordsRoute
  '/rohirat': typeof RohiratRoute
  '/stats': typeof StatsRoute
  '/trophies': typeof TrophiesRoute
  '/virushka': typeof VirushkaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/gallery': typeof GalleryRoute
  '/greatness': typeof GreatnessRoute
  '/ipl': typeof IplRoute
  '/mahirat': typeof MahiratRoute
  '/records': typeof RecordsRoute
  '/rohirat': typeof RohiratRoute
  '/stats': typeof StatsRoute
  '/trophies': typeof TrophiesRoute
  '/virushka': typeof VirushkaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/gallery'
    | '/greatness'
    | '/ipl'
    | '/mahirat'
    | '/records'
    | '/rohirat'
    | '/stats'
    | '/trophies'
    | '/virushka'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/gallery'
    | '/greatness'
    | '/ipl'
    | '/mahirat'
    | '/records'
    | '/rohirat'
    | '/stats'
    | '/trophies'
    | '/virushka'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/gallery'
    | '/greatness'
    | '/ipl'
    | '/mahirat'
    | '/records'
    | '/rohirat'
    | '/stats'
    | '/trophies'
    | '/virushka'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRoute
  GalleryRoute: typeof GalleryRoute
  GreatnessRoute: typeof GreatnessRoute
  IplRoute: typeof IplRoute
  MahiratRoute: typeof MahiratRoute
  RecordsRoute: typeof RecordsRoute
  RohiratRoute: typeof RohiratRoute
  StatsRoute: typeof StatsRoute
  TrophiesRoute: typeof TrophiesRoute
  VirushkaRoute: typeof VirushkaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/greatness': {
      id: '/greatness'
      path: '/greatness'
      fullPath: '/greatness'
      preLoaderRoute: typeof GreatnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl': {
      id: '/ipl'
      path: '/ipl'
      fullPath: '/ipl'
      preLoaderRoute: typeof IplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahirat': {
      id: '/mahirat'
      path: '/mahirat'
      fullPath: '/mahirat'
      preLoaderRoute: typeof MahiratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rohirat': {
      id: '/rohirat'
      path: '/rohirat'
      fullPath: '/rohirat'
      preLoaderRoute: typeof RohiratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virushka': {
      id: '/virushka'
      path: '/virushka'
      fullPath: '/virushka'
      preLoaderRoute: typeof VirushkaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRoute,
  GalleryRoute: GalleryRoute,
  GreatnessRoute: GreatnessRoute,
  IplRoute: IplRoute,
  MahiratRoute: MahiratRoute,
  RecordsRoute: RecordsRoute,
  RohiratRoute: RohiratRoute,
  StatsRoute: StatsRoute,
  TrophiesRoute: TrophiesRoute,
  VirushkaRoute: VirushkaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
